blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/talkstream/ru-text/discussions
    about: Use discussions for questions about rules, usage, or integration
