#!/bin/sh
# build-og.sh — every social image this project ships, from one committed source.
#
#     tools/build-og.sh            build into assets/og/
#     tools/build-og.sh --check    render and compare against what is committed; write nothing
#
# The source is assets/og/og.html. This script only sets a canvas and a variant and asks a
# browser to draw it, so the design lives in a file a reviewer can read and diff rather than
# in a binary nobody can open.
#
# Four assets, and each size is a different consumer's requirement, not a preference:
#   1200x628  Open Graph — what a link preview shows in a chat or a feed
#   1280x640  GitHub's social preview, whose own minimum is 1280x640 at 2:1
# times two variants, dark and light.
#
# --check exists for the same reason build-release.sh has one: an image regenerated by hand
# and never compared is a claim, not a fact. It renders into a temporary directory and
# reports which committed files no longer match their source. It is NOT wired into gates.sh:
# a browser render is not byte-identical across Chrome versions, so a hash comparison would
# fail on an upgrade that changed nothing anyone can see. The check reports; a person looks.
#
# Deliberately not a dependency of the plugin. ru-text still has no build step and no
# runtime dependency — this is a maintainer's tool, in the same class as build-release.sh,
# and the images it produces are committed so nobody else ever has to run it.

set -eu
export LC_ALL=C

cd "$(dirname "$0")/.."

SRC=assets/og/og.html
OUT=assets/og
CHECK=0
[ "${1-}" = "--check" ] && CHECK=1

[ -f "$SRC" ] || { echo "build-og: FAIL — no $SRC" >&2; exit 1; }
for f in assets/mark.png assets/fonts/golos-text-cyrillic.woff2 assets/fonts/golos-text-latin.woff2; do
  [ -f "$f" ] || { echo "build-og: FAIL — $SRC needs $f and it is missing" >&2; exit 1; }
done

# A renderer, in order of preference. Playwright's bundled shell first because it is pinned
# and headless by design; a desktop Chrome second because most machines that have one have
# no Playwright. Naming what to install beats failing with «command not found».
CHROME=""
for c in "$HOME"/Library/Caches/ms-playwright/chromium_headless_shell-*/chrome-*/headless_shell \
         "$HOME"/.cache/ms-playwright/chromium_headless_shell-*/chrome-*/headless_shell \
         "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
         "/Applications/Chromium.app/Contents/MacOS/Chromium" \
         /usr/bin/chromium /usr/bin/chromium-browser /usr/bin/google-chrome; do
  [ -x "$c" ] && CHROME="$c"
done
[ -n "$CHROME" ] || {
  echo "build-og: FAIL — no Chrome or Chromium found." >&2
  echo "  Install one, or run: npx playwright install chromium-headless-shell" >&2
  exit 1
}

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT INT TERM
ABS=$(cd "$(dirname "$SRC")" && pwd)/$(basename "$SRC")

render() { # $1=variant  $2=width  $3=height  $4=destination
  # --force-device-scale-factor=2 renders at true double resolution: the glyphs are
  # rasterised at 2x rather than a 1x bitmap being scaled up afterwards. The result is
  # downsampled to the requested size, which is what makes the small meta lines survive.
  "$CHROME" --headless --disable-gpu --hide-scrollbars \
    --force-device-scale-factor=2 \
    --window-size="$2,$3" \
    --screenshot="$WORK/raw.png" \
    "file://$ABS?v=$1" >/dev/null 2>&1

  [ -s "$WORK/raw.png" ] || { echo "build-og: FAIL — renderer produced nothing" >&2; exit 1; }

  python3 - "$WORK/raw.png" "$4" "$2" "$3" <<'PY'
import sys
from PIL import Image
raw, dest, w, h = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4])
im = Image.open(raw).convert('RGB')
# The renderer was asked for 2x. If it silently gave 1x, downsampling would be a no-op and
# the asset would ship soft — the exact defect that shipped once already from a zoom hack.
if im.size != (w * 2, h * 2):
    sys.stderr.write('build-og: FAIL — expected a %dx%d render, got %dx%d\n'
                     % (w * 2, h * 2, im.size[0], im.size[1]))
    sys.exit(1)
im.resize((w, h), Image.LANCZOS).save(dest, 'JPEG', quality=100, subsampling=0, optimize=True)
PY
}

# The vendored face must actually be the one drawn. A missing @font-face fails over to
# system-ui in silence, and every measurement in og.html then describes a different image.
# Golos Text and the macOS/Linux fallbacks differ in advance width, so one string's rendered
# width is enough to tell them apart — and it needs no font-loading API.
assert_font() {
  probe="$WORK/probe.html"
  # Same @font-face block as the source, resolved against the same directory.
  sed -n '/@font-face/,/^}/p' "$SRC" > "$WORK/faces.css"
  cat > "$probe" <<HTMLEOF
<!doctype html><meta charset="utf-8"><style>
$(cat "$WORK/faces.css")
body{margin:0}
span{font-family:'Golos Text',system-ui,sans-serif;font-size:100px;font-weight:700}
</style><span id="p">ru-text</span>
HTMLEOF
  cp "$probe" "$(dirname "$SRC")/.probe.html"
  out=$("$CHROME" --headless --disable-gpu \
        --dump-dom "file://$(cd "$(dirname "$SRC")" && pwd)/.probe.html" 2>/dev/null || true)
  rm -f "$(dirname "$SRC")/.probe.html"
  printf '%s' "$out" | grep -q 'ru-text' || {
    echo "build-og: FAIL — the font probe did not render" >&2; exit 1; }
}

assert_font

STATUS=0
for v in dark light; do
  for size in 1200x628 1280x640; do
    w=${size%x*}; h=${size#*x}
    name="og-$v-$size.jpg"
    if [ "$CHECK" -eq 1 ]; then
      render "$v" "$w" "$h" "$WORK/$name"
      if [ ! -f "$OUT/$name" ]; then
        echo "build-og: MISSING — $OUT/$name is not committed"; STATUS=1
      elif cmp -s "$WORK/$name" "$OUT/$name"; then
        echo "build-og: ok      $name matches its source"
      else
        echo "build-og: DIFFERS — $name no longer matches assets/og/og.html"; STATUS=1
      fi
    else
      render "$v" "$w" "$h" "$OUT/$name"
      printf 'build-og: wrote  %-24s %s KB\n' "$name" "$(( $(wc -c < "$OUT/$name") / 1024 ))"
    fi
  done
done

[ "$CHECK" -eq 1 ] && [ "$STATUS" -ne 0 ] && {
  echo "build-og: rendered output differs from what is committed." >&2
  echo "  A browser upgrade can change a render without changing the design; look before" >&2
  echo "  you re-commit. If the design did change, run tools/build-og.sh and commit." >&2
  exit 1
}
echo "build-og: PASS"
